<style>
    a:link,
    a:visited
    {
        color: #000000;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>
<div id="welcome">
    <h1>Welcome to the <span id="zf-name">HNA Base!</span></h1>

    <h3><a href="/hna/index">hna-index</a>
            <a href="/hna/add">hna-add</a>
            <a href="/pays/add">pays-add</a>
</h3>

    <div id="more-information">
        <br />
        Для того что бы добавить пользователя необходимо авторизоваться. <br />
        <table align="center">
            <tr align="left">
                <td>Login:</td>
                <td>hnaadmin</td>
            </tr>
            <tr align="left">
                <td>Pass:</td>
                <td>666hacker90</td>
            </tr>

        </table>

        <br /><br /><br /><br /><br /><br />
        <p><img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>
        <p>
            <br /><br /><br />
        </p>
    </div>
</div>