<style>
    a:link,
    a:visited
    {
        color: #000000;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 780px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>
<center>
<h1>Welcome to the <span id="zf-name">HNA Base!</span></h1>
<p><img src="/images/zog.jpeg" /></p>
<p><img src="/images/zf.png" /></p>
</center>