<p>Are you sure taht you want to delete
	<?php echo $this->escape($this->user['surname']); ?> <?php echo $this->escape($this->user['firstname']); ?> ?
</p>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
<div>
	<input type="hidden" name="id" value="<?php echo $this->user['id']; ?>" />
	<input type="submit" name="del" value="Yes" />
	<input type="submit" name="del" value="No" />
</div>
</form> 