<p>Вы действительно хотите удалить пользователя?<br>
	<?php echo $this->escape($this->user['surname']); ?>
        <?php echo $this->escape($this->user['firstname']); ?>
        <?php echo $this->escape($this->user['lastname']); ?> <br>
        <?php echo $this->escape($this->user['group']); ?> <br>
        <?php echo $this->escape($this->user['ip']); ?> <br>
        <?php echo $this->escape($this->user['block']); ?>
        <?php echo $this->escape($this->user['room']); ?> <br>
        <?php echo $this->escape($this->user['note']); ?>

</p>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
<div>
	<input type="hidden" name="user_id" value="<?php echo $this->user['user_id']; ?>" />
	<input type="submit" name="del" value="Yes" />
	<input type="submit" name="del" value="No" />
</div>
</form> 