<style type="text/css">
table,td,th {
	border: 1px solid black;
	border-collapse: collapse;     
}
</style>
<center>
<table style="font-size: 16px;">
<tr>
        <th style="width: 40px;">ID</th>
	<th style="width: 250px;">Фамилия Имя Отчество</th>
	<th style="width: 40px;">Дог.</th>
        <th style="width: 60px;">Логин</th>
        <th style="width: 45px;">Группа</th>
        <th style="width: 40px;">Комн.</th>
	<th style="width: 50px;">Дата рег.</th>
        <th style="width: 70px;">Админ.</th>
        <th style="width: 70px;">Посл. IP</th>
        <th style="width: 100px;">Посл. MAC</th>
	<th style="width: 300px;">Примечание</th>
	<th>&nbsp;</th>	
</tr>
<?php foreach($this->hna as $users) : ?>
<tr style="background-color: <?php
                                switch ($users->status) {
                                case 1:
                                    echo '#ff8c69';
                                    break;
                                case 2:
                                    echo '#abcdef';
                                    break;
                                case 3:
                                    echo '#77dd77';
                                    break;
                                default:
                                    echo '#ffffff';
                                    break;
                                }
                             ?>;">
        <td><?php echo $this->escape($users->user_id); ?></td>
	<td><?php echo $this->escape($users->surname).' '.$this->escape($users->firstname).' '.$this->escape($users->lastname);?></td>
	<td><?php echo $this->escape($users->contract); ?></td>
        <td><?php echo $this->escape($users->login); ?></td>
        <td><?php echo $this->escape($users->group); ?></td>
	<td><?php echo $this->escape($users->block).$this->escape($users->room); ?></td>
	<td><?php echo $this->escape($users->register); ?></td>
        <td><?php echo $this->escape($this->admin[$this->escape($users->admin_id)]); ?></td>
        <td><?php echo $this->escape($users->lastip); ?></td>
        <td><?php echo $this->escape($users->lastmac); ?></td>
	<td><?php echo $this->escape($users->note); ?></td>
	<td><a href="<?php echo $this->url(array('controller'=>'hna','action'=>'edit','user_id'=>$users->user_id)); ?>">Edit</a> <a href="<?php echo $this->url(array('controller'=>'hna','action'=>'view','user_id'=>$users->user_id)); ?>">View</a></td>
</tr>
<?php endforeach;?>


</table>
</center>