<style type="text/css">
table,td,th {
	border: 1px solid black;
	border-collapse: collapse;
}
</style>
<center>
<table>
<tr>
        <th>ID</th>
	<th>Name</th>
	<th>Contract</th>
        <th>Login</th>
        <th>Group</th>
        <th>Block</th>
	<th>status</th>
	<th>date_reg</th>
        <th>admin</th>
	<th>note</th>	
	<th>&nbsp;</th>	
</tr>
<?php foreach($this->hna as $users) : ?>
<tr>
        <td><?php echo $this->escape($users->user_id); ?></td>
	<td><?php echo $this->escape($users->surname).' '.$this->escape($users->firstname).' '.$this->escape($users->lastname);?></td>
	<td><?php echo $this->escape($users->contract); ?></td>
        <td><?php echo $this->escape($users->login); ?></td>
        <td><?php echo $this->escape($users->group); ?></td>
	<td><?php echo $this->escape($users->block).$this->escape($users->room); ?></td>
	<td><?php echo $this->escape($users->status); ?></td>
	<td><?php echo $this->escape($users->register); ?></td>
        <td><?php echo $this->escape($this->admin[$this->escape($users->admin_id)]); ?></td>
	<td><?php echo $this->escape($users->note); ?></td>
	<td><a href="<?php echo $this->url(array('controller'=>'hna','action'=>'edit','user_id'=>$users->user_id)); ?>">Edit</a> <a href="<?php echo $this->url(array('controller'=>'hna','action'=>'view','user_id'=>$users->user_id)); ?>">View</a></td>
</tr>
<?php endforeach;?>


</table>
</center>