
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        oTable = $('#data').dataTable({
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "bStateSave": true,
            "aLengthMenu": [[10, 20, 30, 40, 50, 100, -1], [10, 20, 30, 40, 50, 100, "All"]],
        });
    });
</script>
<center>
<div class="demo_jui">
<table id="data" cellpadding="0" cellspacing="0" border="0" class="display" style="width: 99%;">
<thead>
<tr>
    <th>ID</th>
	<th>Фамилия Имя Отчество</th>
    <th>Логин</th>
    <th>Группа</th>
    <th>Комн.</th>
	<th>Дата рег.</th>
    <th>Свич</th>
    <th>Посл. IP</th>
    <th>Посл. MAC</th>
	<th>Примечание</th>
	<th>&nbsp;</th>
</tr>
</thead>
<tbody>
<?php foreach($this->hna as $users) : ?>
<tr class="<?php
                                switch ($users->status) {
                                case 1:
                                    echo 'gradeX';
                                    break;
                                case 2:
                                    echo 'gradeC';
                                    break;
                                case 3:
                                    echo 'gradeA';
                                    break;
                                default:
                                    echo 'default';
                                    break;
                                }
                             ?>">
    <td><?php echo $this->escape($users->user_id); ?></td>
	<td><?php echo $this->escape($users->surname).' '.$this->escape($users->firstname).' '.$this->escape($users->lastname);?></td>
    <td><?php echo $this->escape($users->login); ?></td>
    <td><?php echo $this->escape($users->group); ?></td>
	<td><?php echo 'h'.$this->escape($users->hostel).' '.$this->escape($users->block).$this->escape($users->room); ?></td>
	<td><?php echo $this->escape($users->register); ?></td>
    <td <?php if($users->switch_id != 0) echo 'class="switch"'; ?> title="<?php echo $this->escape($users->switch_id); ?>"></td>
    <td><?php echo $this->escape($users->lastip); ?></td>
    <td><?php echo $this->escape($users->lastmac); ?></td>
	<td><?php


            echo substr($users->note, 0, 40); ?></td>
	<td><a class="edit" href="<?php echo $this->url(array('controller'=>'hna','action'=>'edit','user_id'=>$users->user_id)); ?>" title="Редактировать"></a>
        <a class="view" href="<?php echo $this->url(array('controller'=>'hna','action'=>'view','user_id'=>$users->user_id)); ?>" title="Просмотреть"></a></td>
</tr>
<?php endforeach;?>

</tbody>
</table>
</center>