<style type="text/css">
table,td,th {
	border: 1px solid black;
	border-collapse: collapse;
}
#pay {
        background-image: url('/images/checked.png');
        background-repeat: no-repeat;
        background-position: center;
        width: 45px;
}
#nopay {
        background-image: url('/images/unchecked.png');
        background-repeat: no-repeat;
        background-position: center;
        width: 45px;
}
.cable {
        background-image: url('/images/cable.png');
        background-repeat: no-repeat;
        background-position: center;
        width: 45px;
}
.switch {
        background-image: url('/images/switch.png');
        background-repeat: no-repeat;
        background-position: center;
        width: 45px;
}
</style>
<center>
<table>
<tr>
	<th>№ дог.</th>
	<th>Фамилия Имя Отчество</th>
        <th>Группа</th>
        <th>Комната</th>
	<th>Регистр.</th>
        <th>Подкл.</th>
        <th>Сент.</th>
        <th>Окт.</th>
        <th>Нояб.</th>
        <th>Дек.</th>
        <th>Янв.</th>
        <th>Февр.</th>
        <th>Март</th>
        <th>Апр.</th>
        <th>Май</th>
        <th>Июнь</th>
        <th>Июль</th>
        <th>Авг.</th>
    <th>Каб.</th>
    <th>Свич.</th>

</tr>
<?php foreach($this->hna as $users) : ?>
<tr style="background-color: <?php if($users['status'] == 1){echo '#ff8c69';} else {echo '#ffffff';}; ?>;">
	<td><?php echo $this->escape($users['contract']); ?></td>
	<td><?php echo $this->escape($users['surname']).' '.$this->escape($users['firstname']).' '.$this->escape($users['lastname']);?></td>
        <td><?php echo $this->escape($users['group']); ?></td>
	<td><?php echo 'h'.$this->escape($users['hostel']).' '.$this->escape($users['block']).$this->escape($users['room']); ?></td>
	<td><?php echo $this->escape($users['register']); ?></td>
        <td id="<?php if($users['connect']){ echo 'pay';} else {echo 'nopay';} ?>" title="Подключение"></td>
        <td id="<?php if($users['9']){ echo 'pay';} else {echo 'nopay';} ?>" title="Сентябрь"></td>
        <td id="<?php if($users['10']){ echo 'pay';} else {echo 'nopay';} ?>" title="Отябрь"></td>
        <td id="<?php if($users['11']){ echo 'pay';} else {echo 'nopay';} ?>" title="Ноябрь"></td>
        <td id="<?php if($users['12']){ echo 'pay';} else {echo 'nopay';} ?>" title="Декабрь"></td>
        <td id="<?php if($users['1']){ echo 'pay';} else {echo 'nopay';} ?>" title="Январь"></td>
        <td id="<?php if($users['2']){ echo 'pay';} else {echo 'nopay';} ?>" title="Февраль"></td>
        <td id="<?php if($users['3']){ echo 'pay';} else {echo 'nopay';} ?>" title="Март"></td>
        <td id="<?php if($users['4']){ echo 'pay';} else {echo 'nopay';} ?>" title="Апрель"></td>
        <td id="<?php if($users['5']){ echo 'pay';} else {echo 'nopay';} ?>" title="Май"></td>
        <td id="<?php if($users['6']){ echo 'pay';} else {echo 'nopay';} ?>" title="Июнь"></td>
        <td id="<?php if($users['7']){ echo 'pay';} else {echo 'nopay';} ?>" title="Июль"></td>
        <td id="<?php if($users['8']){ echo 'pay';} else {echo 'nopay';} ?>" title="Август"></td>
        <td <?php if($users['cable'] == 1) echo 'class="cable"'; ?>></td>
        <td <?php if($users['switch_id'] != 0) echo 'class="switch"'; ?> title="<?php if($users['switch_id'] != 0) echo $this->escape($users['switch_id']); ?>"></td>
</tr>
<?php endforeach;?>


</table>
</center>