Информация о пользователе: <br>

ФИО:        <?php echo $this->escape($this->user['surname']); ?>
            <?php echo $this->escape($this->user['firstname']); ?>
            <?php echo $this->escape($this->user['lastname']); ?> <br>
Договор:    <?php echo $this->escape($this->user['contract']); ?> <br>
Login:      <?php echo $this->escape($this->user['contract']) .$this->escape($this->user['login']); ?> <br>
Password:   <?php echo $this->escape($this->user['pass']); ?> <br>
Группа:     <?php echo $this->escape($this->user['group']); ?> <br>
Блок:       <?php echo $this->escape($this->user['block']); ?>
            <?php echo $this->escape($this->user['room']); ?> <br>
Примечание: <?php echo $this->escape($this->user['note']); ?>
<br><br>
Подключение: <?php echo $this->escape($this->pay['connect']); ?> <br>
Сент: <?php echo $this->escape($this->pay['9']); ?> <br>
Окт: <?php echo $this->escape($this->pay['10']); ?> <br>
Ноябр: <?php echo $this->escape($this->pay['11']); ?> <br>
Дек: <?php echo $this->escape($this->pay['12']); ?> <br>
Янв: <?php echo $this->escape($this->pay['1']); ?> <br>
Февр: <?php echo $this->escape($this->pay['2']); ?> <br>
Март: <?php echo $this->escape($this->pay['3']); ?> <br>
Апр: <?php echo $this->escape($this->pay['4']); ?> <br>
Май: <?php echo $this->escape($this->pay['5']); ?> <br>
Июн: <?php echo $this->escape($this->pay['6']); ?> <br>
Июл: <?php echo $this->escape($this->pay['7']); ?> <br>
Авг: <?php echo $this->escape($this->pay['8']); ?> <br>