<style type="text/css">
table,td,th {
	border: 1px solid black;
	border-collapse: collapse;
}
#pay {
        background-image: url('/images/checked.png');
        background-repeat: no-repeat;
        background-position: center;
        width: 45px;
        height: 20px;
}
#nopay {
        background-image: url('/images/unchecked.png');
        background-repeat: no-repeat;
        background-position: center;
        width: 45px;
        height: 20px;
}
</style>
Информация о пользователе: <br>
<table>
    <tr>
        <td>
            ФИО:
        </td>
        <td>
            <?php echo $this->escape($this->user['surname']); ?>
            <?php echo $this->escape($this->user['firstname']); ?>
            <?php echo $this->escape($this->user['lastname']); ?>
        </td>
    </tr>
    <tr>
        <td>
            Договор:
        </td>
        <td>
            <?php echo $this->escape($this->user['contract']); ?>
        </td>
    </tr>
    <tr>
        <td>
            Логин:
        </td>
        <td>
            <?php echo $this->escape($this->user['login']); ?>
        </td>
    </tr>
    <tr>
        <td>
            Пароль:
        </td>
        <td>
           <?php
                if ($this->user['status'] == 3){
                    echo "&lt;hidden&gt;";
                } else {
                    echo $this->escape($this->user['pass']);
                }
            ?>
        </td>
    </tr>
    <tr>
        <td>
            Группа:
        </td>
        <td>
            <?php echo $this->escape($this->user['group']); ?>
        </td>
    </tr>
    <tr>
        <td>
            Общежитие:
        </td>
        <td>
            №<?php echo $this->escape($this->user['hostel']); ?>
        </td>
    </tr>
    <tr>
        <td>
            Блок:
        </td>
        <td>
            <?php echo $this->escape($this->user['block']) . $this->escape($this->user['room']); ?>
        </td>
    </tr>
    <tr>
        <td>
            Кабель:
        </td>
        <td>
            <?php if($this->user['cable'] == 1) echo 'Выдан'; ?>
        </td>
    </tr>
    <tr>
        <td>
            Свич №:
        </td>
        <td>
            <?php if($this->user['switch_id'] != 0) echo $this->user['switch_id']; ?>
        </td>
    </tr>
    <tr>
        <td>
            Примечание:
        </td>
        <td>
            <?php echo $this->escape($this->user['note']); ?>
        </td>
    </tr>
</table>

<br>

Оплаты:
<table>
<tr style="">
        <th>Подкл.</th>
        <th>Сент.</th>
        <th>Окт.</th>
        <th>Нояб.</th>
        <th>Дек.</th>
        <th>Янв.</th>
        <th>Февр.</th>
        <th>Март</th>
        <th>Апр.</th>
        <th>Май</th>
        <th>Июнь</th>
        <th>Июль</th>
        <th>Авг.</th>

</tr>
<tr style="">
        <td id="<?php if($this->pay['connect']){ echo 'pay';} else {echo 'nopay';} ?>"></td>
        <td id="<?php if($this->pay['9']){ echo 'pay';} else {echo 'nopay';} ?>"></td>
        <td id="<?php if($this->pay['10']){ echo 'pay';} else {echo 'nopay';} ?>"></td>
        <td id="<?php if($this->pay['11']){ echo 'pay';} else {echo 'nopay';} ?>"></td>
        <td id="<?php if($this->pay['12']){ echo 'pay';} else {echo 'nopay';} ?>"></td>
        <td id="<?php if($this->pay['1']){ echo 'pay';} else {echo 'nopay';} ?>"></td>
        <td id="<?php if($this->pay['2']){ echo 'pay';} else {echo 'nopay';} ?>"></td>
        <td id="<?php if($this->pay['3']){ echo 'pay';} else {echo 'nopay';} ?>"></td>
        <td id="<?php if($this->pay['4']){ echo 'pay';} else {echo 'nopay';} ?>"></td>
        <td id="<?php if($this->pay['5']){ echo 'pay';} else {echo 'nopay';} ?>"></td>
        <td id="<?php if($this->pay['6']){ echo 'pay';} else {echo 'nopay';} ?>"></td>
        <td id="<?php if($this->pay['7']){ echo 'pay';} else {echo 'nopay';} ?>"></td>
        <td id="<?php if($this->pay['8']){ echo 'pay';} else {echo 'nopay';} ?>"></td>
</tr>
</table>

<br />
История пользователя:

<style type="text/css">
    table,td,th {
	border: 1px solid black;
	border-collapse: collapse;
}
</style>

<table style="font-size: 11px;">
    <tr>
        <th>Дата:</th>
        <th>Администратор:</th>
        <th>Событие:</th>
        <th>Сообщение:</th>
    </tr>
<?php foreach($this->log as $logs) : ?>
    <tr>
        <td><?php echo $this->escape($logs['time']); ?></td>
        <td><?php echo $this->escape($this->admin[$this->escape($logs['admin_id'])]); ?></td>
        <td><?php
                switch ($logs['action']) {
                    case 0: echo "Создание пользователя"; break;
                    case 1: echo "Востановление пользователя из архива"; break;
                    case 2: echo "Редактирование пользователя"; break;
                    case 3: echo "Добавление оплаты"; break;
                }
            ?></td>
        <td><?php echo $this->escape($logs['message']); ?></td>
    </tr>
<?php endforeach;?>
</table>
