<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <?php echo $this->headTitle(); ?>
        
        <?php if($this->dojo()->isEnabled()):
                $this->dojo()->setLocalPath('/js/dojo/dojo.js')
                    ->addStyleSheetModule('dijit.themes.tundra');
                echo $this->dojo();
              endif; ?>
    </head>
    <body class="tundra">

        <div id="header">
        <table style="width: 99%; border: 0px; ">
            <tr>
                <td style="text-align: left; border: 0px;">
                    <a href="/hna/index">hna-index</a>
                    <a href="/hna/add">hna-add</a>
                    <a href="/pays/add">pays-add</a>
                </td>
                <td style="text-align: rigth; border: 0px;">
                    <div id="logged-in-as" style="text-align: right;">
                        <?php echo $this->loggedAs(); ?>
                    </div>
                </td>
            </tr>
        </table>
        <br />
        </div>
        <div>
            <?php echo $this->layout()->content; ?>
            
        </div>
    </body>
</html>