<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <link href="/images/favicon.ico" rel="icon" type="image/x-icon" />
        <link rel="stylesheet" type="text/css" href="/css/styles.css">  

	    <style type="text/css" title="currentStyle">
			@import "/css/demo_page.css";
			@import "/css/demo_table_jui.css";
			@import "/css/smoothness/jquery-ui-1.8.4.custom.css";
		</style>

		<script type="text/javascript" language="javascript" src="/js/jquery.js"></script>
		<script type="text/javascript" language="javascript" src="/js/jquery.dataTables.js"></script>
			
        <?php echo $this->headTitle(); ?>
        
        <?php if($this->dojo()->isEnabled()):
                $this->dojo()->setLocalPath('/js/dojo/dojo.js')
                    ->addStyleSheetModule('dijit.themes.tundra');
                echo $this->dojo();
              endif; ?>
    </head>
    <body class="tundra">

        <div id="header">
        <table style="width: 99%; border: 0px; ">
            <tr>
                <td style="text-align: left; border: 0px;">
                    <a href="/hna/index">Активные пользователи</a>
                    <a href="/hna/arch">Архивные пользователи</a>
                    <a href="/hna/add">Добавить пользователя</a>
                    <a href="/pays/add">Добавить оплату</a>
                    <a href="/hna/payslist">Список оплат</a>
                    <a href="/statistic">Статистика</a>
                </td>
                <td style="text-align: rigth; border: 0px;">
                    <div id="logged-in-as" style="text-align: right;">
                        <?php echo $this->loggedAs(); ?>
                    </div>
                </td>
            </tr>
        </table>
        <br />
        </div>
        <div>
            <?php echo $this->layout()->content; ?>
            
        </div>
    </body>
</html>